// 11 бейджей
// passType  — большой жирный заголовок на карточке
// title     — заголовок в модале
// cats      — фильтры: priemka | teach | organizer | participant
window.BADGES = [
  {
    id: 'sport',
    org: 'ITMO · KRONBARS · SNOWBOARD',
    passType: 'СБОРНАЯ ПО СНОУБОРДУ',
    period: '2020 — 2022',
    venue: 'ITMO · ski team',
    icon: '🏂',
    regNo: 'KB.SNOW.19',
    bg: '#0d0d0d', fg: '#ffffff', accent: '#4f7cff',
    ribbon: '#1a3a8a', ribbonPattern: 'lines',
    pattern: 'diag',
    cats: ['participant'],
    eyebrow: 'СПОРТ · 2020—2022',
    title: 'Сборная Универа по сноуборду',
    color: '#1a1a1a', darkHeader: true,
    body: '<p>В Университет я пришла с небольшим спортивным сноубордическим прошлым. Когда увидела отбор в сборную ИТМО по горнолыжному спорту — не раздумывая подалась. Пройдя отбор, стала членом сборной по сноуборду.</p><p>Мы много тренировались, учились друг у друга новому, проводили выходные на склоне. С командой принимали участие в Универсиадах и других студенческих соревнованиях.</p>',
    tags: ['сборная', 'сноуборд', 'тренировки', 'соревнования'],
    stats: [['2', 'сезона'], ['∞', 'выходных на склоне']],
    photos: [
      ['images/sport/1_IMG_2784.PNG', 'соревнование'],
      ['images/sport/2_IMG_5120.jpg', 'тренировка'],
      ['images/sport/3_IMG_2789.jpg', 'на склоне'],
    ]
  },

  {
    id: 'ambassador',
    org: 'YANDEX × ITMO · I COHORT',
    passType: 'АМБАССАДОР ЯНДЕКСА',
    period: '2022 — 2024',
    venue: 'pilot programme · ITMO',
    icon: '👾',
    regNo: 'YA.AMB.I',
    bg: '#fdd335', fg: '#0d0d0d', accent: '#ff7700',
    ribbon: '#0d0d0d', ribbonPattern: 'dots',
    pattern: 'circles',
    cats: ['organizer', 'participant'],
    stamp: 'PILOT',
    eyebrow: 'АМБАССАДОР · 2022—2024',
    title: 'Амбассадор Яндекса',
    color: '#ffd23a', darkHeader: false,
    body: '<p>Стала участником <b>первого набора</b> программы амбассадоров Яндекса и выступала связующим звеном между компанией и студентами ИТМО.</p><p>Организовывала мероприятия в Универе и знакомила ребят с компанией и карьерными возможностями: выдавала рефералки на стажировку и помогала ребятам получить первую работу в компании мечты.</p>',
    tags: ['пилотный набор', 'нетворкинг', 'рефералки', 'YungCon'],
    stats: [],
    photos: [
      ['images/ambassador/1_IMG_9222.jpg', 'мероприятие Яндекса'],
      ['images/ambassador/2_IMG_9162.jpg', 'офис Яндекса'],
      ['images/ambassador/3_IMG_8795.jpg', 'амбассадоры ИТМО'],
      ['images/ambassador/4_IMG_0542.jpg', 'нетворкинг'],
      ['images/ambassador/5_IMG_6619.JPG', 'событие'],
    ]
  },

  {
    id: 'priemka1',
    org: 'ITMO · ADMISSIONS COMMITTEE',
    passType: 'ПРИЕМНАЯ КОМИССИЯ',
    period: '2021 — 2025',
    venue: 'admissions · 4 years',
    icon: '🤍',
    regNo: 'ADM.2020',
    bg: '#f5e69b', fg: '#2a1d00', accent: '#ffb800',
    ribbon: '#b89200', ribbonPattern: 'waves',
    pattern: 'waves',
    cats: ['priemka'],
    eyebrow: 'ПРИЁМКА · 2021—2025',
    title: 'Приемная комиссия',
    color: '#ffd23a', darkHeader: false,
    body: '<p>Случайно попав на день открытых дверей однажды, не смогла остановиться 💔</p><p>Так на целых <b>4 года</b> я попала в ✨приёмную комиссию ИТМО✨</p><p>Каждый день общалась с абитуриентами, рассказывала про университет, наши направления и поступление. Кажется, что это работа мечты — рассказывать, почему я так люблю наш Универ и всем очень нужно к нам поступить.</p>',
    tags: ['работа мечты', 'абитуриенты', 'консультации'],
    stats: [],
    photos: [
      ['images/admission/1_IMG_4095.jpg', 'команда приемки 2022'],
      ['images/admission/2_IMG_4272.PNG', 'приемная комиссия'],
      ['images/admission/3_IMG_3187.jpg', 'команда приёмки 2023'],
      ['images/admission/4_IMG_4252.PNG', 'приемная комиссия'],
      ['images/admission/5_IMG_7989.jpg', 'День Открытых Дверей'],
      ['images/admission/6_IMG_3214.PNG', 'Кронверкский, 49'],
    ]
  },

  {
    id: 'priemka2',
    org: 'PIKT · ADMISSIONS LEAD',
    passType: 'МЕНЕДЖЕР ПИиКТ',
    period: '2023 — 2025',
    venue: 'PIKT · 2000+ enrolled',
    icon: '★',
    regNo: 'PIKT.ADM',
    bg: '#e84a1f', fg: '#ffffff', accent: '#ffd23a',
    ribbon: '#ff8a3d', ribbonPattern: 'stripes',
    pattern: 'stripes',
    cats: ['priemka'],
    stamp: '★ HEART',
    eyebrow: 'ПРИЁМКА · ПИиКТ · 2023—2025',
    title: 'Менеджер факультета ПИиКТ',
    color: '#ff6b3d', darkHeader: false,
    body: '<p>Через несколько лет в приёмке я стала ответственной за приём на бакалавриат на свой факультет ПИиКТ.</p><p>Выросла не только зона ответственности, но и моя любовь к этой работе. Теперь я курировала процессы поступления сотен абитуриентов, следила за нашим набором, проходными баллами и помогала абитуриентам сделать такой непростой, но очень важный выбор.</p><p>За это время мы зачислили <b>больше 2000 первокурсников</b> и провели <b>больше 100 мероприятий</b>. Это был чудесный период. В ИТМО концентрация классных людей — мне повезло встретить не просто коллег, а настоящих друзей и многому научиться.</p>',
    tags: ['ПИиКТ', 'бакалавриат', 'менеджер', 'команда мечты'],
    stats: [['2000+', 'зачисленных'], ['100+', 'мероприятий'], ['ПИиКТ', '♡']],
    photos: [
      ['images/manager/1_IMG_0509.JPG', 'ДОД выступление'],
      ['images/manager/3_IMG_2275.JPG', 'Прием прием'],
      ['images/manager/4_IMG_2790.JPG', 'ДОД выступление'],
      ['images/manager/5_IMG_2791.JPG', 'Команда приемки 2025'],
      ['images/manager/6_IMG_2792.JPG', 'Профориентация в школе'],
      ['images/manager/7_IMG_3681.jpg', 'Профориентация в школе'],
    ]
  },

  {
    id: 'forums',
    org: 'CASE-CHAMPIONSHIP · SOCHI · MOSCOW',
    passType: 'КЕЙС-ЧЕМПИОНАТЫ',
    period: 'SOCHI · ВТБ',
    venue: '1st place case · 2022—23',
    icon: '🏆',
    regNo: 'FRM.CHMP',
    bg: '#5b1d8a', fg: '#ffffff', accent: '#b454ff',
    ribbon: '#2a0a4a', ribbonPattern: 'waves',
    pattern: 'circles',
    cats: ['participant'],
    stamp: '★ 1st',
    stampClass: 'gold',
    eyebrow: 'ФОРУМЫ · КЕЙСЫ',
    title: 'Кейс-чемпионаты',
    color: '#b454ff', darkHeader: false,
    body: '<p>Не упускала ни одной возможности прокачать свои навыки и познакомиться с крутыми студентами со всей России. А лучший способ — посетить кейс-чемпионаты.</p><p>📍 <b>Форум в Сочи</b> — где мы с командой стали <b>победителями</b> кейс-чемпионата.</p><p>📍 <b>ВТБ форум в Москве</b> — подарил мне незабываемые эмоции, опыт решения интересной задачи и классные знакомства.</p>',
    tags: ['кейс-чемпионат', 'победители', 'Сочи', 'ВТБ', 'Москва'],
    stats: [['1', 'место в Сочи'], ['2', 'форума'], ['∞', 'знакомств']],
    photos: [
      ['images/case/1_IMG_8789.PNG', 'Сочи · победа'],
      ['images/case/2_IMG_2620.jpg', 'команда'],
      ['images/case/3_IMG_2621.PNG', 'решаем кейс'],
      ['images/case/4_IMG_2622.PNG', 'команда ВТБ'],
      ['images/case/5_IMG_8585.JPG', 'команда Сочи'],
      ['images/case/6_IMG_8698.PNG', 'ожидание результатов'],
    ]
  },

  {
    id: 'piktfest',
    org: 'PIKT.FEST · T-БАНК HACKATHON',
    passType: 'ОРГАНИЗАТОР',
    period: '2022 — 2024',
    venue: 'PIKT · 100+ schoolers',
    icon: '🎤',
    regNo: 'PIKT.FEST',
    bg: '#1a1a1a', fg: '#ffd23a', accent: '#ff6b3d',
    ribbon: '#ff6b3d', ribbonPattern: 'dots',
    pattern: 'dots',
    cats: ['priemka', 'organizer'],
    eyebrow: 'ОРГАНИЗАЦИЯ · ПИиКТ',
    title: 'Организатор',
    color: '#ff6b3d', darkHeader: false,
    body: '<p>Чтобы летом набор на факультет прошёл успешно, в течение года с коллегами с факультета занималась организацией крутых мероприятий для абитуриентов.</p><p>В копилке — соорганизация нескольких <b>ПИКТ.Фестов</b>: открытый микрофон, день карьеры и день абитуриента в одном. Старались, чтобы каждое мероприятие приносило пользу и текущим студентам, и будущим.</p><p>Ярким событием стал большой <b>Хакатон с Т-Банком</b>, в котором приняли участие <b>больше 100 школьников</b> со всей России. Готовили для них кейсы, на протяжении нескольких дней наблюдали и поддерживали команды в ИТМО, а лучшим достались ценные призы, включая дополнительные баллы для поступления.</p>',
    tags: ['ПИКТ.Фест', 'Т-Банк', 'хакатон', 'школьники', 'кейсы'],
    stats: [],
    photos: [
      ['images/org/1_IMG_8218.jpg', 'ПИКТ.Фест'],
      ['images/org/2_IMG_8125.JPG', 'открытый микрофон'],
      ['images/org/3_IMG_0110.jpg', 'участник'],
      ['images/org/4_IMG_3360.PNG', 'хакатон с Т-Банком'],
      ['images/org/5_IMG_3980.jpg', 'после мероприятия'],
      ['images/org/6_IMG_8124.JPG', 'победители'],
    ]
  },

  {
    id: 'mentor',
    org: 'WEB DEVELOPMENT · ITMO',
    passType: 'МЕНТОР ПО ВЕБУ',
    period: '2021 · 3rd year',
    venue: 'web course · lab TA',
    icon: '👩‍🏫',
    regNo: 'MNT.WEB',
    bg: '#1f6b4a', fg: '#e8ffd8', accent: '#3fa66a',
    ribbon: '#0c3a26', ribbonPattern: 'lines',
    pattern: 'grid',
    cats: ['teach'],
    eyebrow: 'МЕНТОРСТВО · 3 КУРС',
    title: 'Ментор по веб-программированию',
    color: '#3fa66a', darkHeader: false,
    body: '<p>Уже на 3-м курсе пробовала себя в роли преподавателя — стала <b>ментором по «Веб-программированию»</b>.</p><p>Помогала лектору вести практические занятия, готовила к ним материалы и проверяла лабораторные работы у студентов. Этот опыт помог мне под другим углом взглянуть на обучение и на роль преподавателя.</p>',
    tags: ['веб-программирование', 'ассистент', 'лабораторные'],
    stats: [],
    cover: 'images/web/1_web_programmirovanie.webp',
    photos: [
      ['images/web/12review.png', 'отзывы студентов'],
    ]
  },

  {
    id: 'kalik',
    org: 'ITMO · DELEGATIONS · TRAVEL',
    passType: 'КОМАНДИРОВКИ',
    period: '2022 — 2024',
    venue: 'schools & events · Russia',
    icon: '✈️',
    regNo: 'KLD.EDU',
    bg: '#163b80', fg: '#ffffff', accent: '#4f7cff',
    ribbon: '#0a1f4a', ribbonPattern: 'waves',
    pattern: 'waves',
    cats: ['priemka'],
    eyebrow: 'ВЫЕЗДЫ · ДЕЛЕГАЦИИ',
    title: 'Командировки',
    color: '#4f7cff', darkHeader: false,
    body: '<p>Проводила мероприятия в школах не только Санкт-Петербурга, но и Калининграда! Ездила в составе небольшой делегации в Калининград, чтобы посетить топовые школы и рассказать их ученикам про наш Университет!</p>',
    tags: ['делегация', 'школы', 'выезд', 'представительство'],
    stats: [],
    photos: [
      ['images/trip/1_IMG_2542.jpg', 'командировка'],
      ['images/trip/2_IMG_2793.jpg', 'выезд'],
      ['images/trip/3_IMG_2795.jpg', 'в школе'],
    ]
  },

  {
    id: 'ktuteam',
    org: 'KTU.TEAM · PIKT PROJECT',
    passType: 'KTU.TEAM',
    period: '6 cities · 20+ schools',
    venue: 'all-russia · student ambassadors',
    icon: '🗺',
    regNo: 'KTU.TEAM',
    bg: '#363432', fg: '#f6e9d0', accent: '#ffd23a',
    ribbon: '#1a1a1a', ribbonPattern: 'dots',
    pattern: 'dots',
    cats: ['priemka', 'organizer'],
    stamp: '×20 ШКОЛ',
    eyebrow: 'ПРОЕКТ · 6 ГОРОДОВ',
    title: 'KTU.TEAM',
    color: '#6e6a5e', darkHeader: false,
    body: '<p>Вместе с коллегами создали проект <b>КТУ.TEAM</b>, в котором наши студенты факультета посещали свои школы, рассказывали про процесс поступления, про учёбу, про Университет и помогали школьникам узнать про наш Универ, программы и определиться с поступлением.</p><p>Мы помогали инициативным студентам, проводили для них обучение, готовили материалы для посещения школы и пробовали разные форматы выступлений.</p><p>Мы смогли охватить <b>6 городов и больше 20 школ</b> по всей стране.</p>',
    tags: ['КТУ.TEAM', 'студенты в школах', '6 городов', 'формат'],
    stats: [['6', 'городов'], ['20+', 'школ']],
    photos: [
      ['images/ktuteam/1_IMG_3341.PNG', 'КТУ.TEAM'],
      ['images/ktuteam/2_IMG_2935.jpg', 'выезд в школу'],
      ['images/ktuteam/3_IMG_2799.JPG', 'студенты у себя в школе'],
      ['images/ktuteam/4_IMG_2796.JPG', 'студенты у себя в школе'],
      ['images/ktuteam/5_IMG_2797.JPG', 'выступление'],
      ['images/ktuteam/6_IMG_2801.JPG', 'студенты у себя в школе'],
    ]
  },

  {
    id: 'china',
    org: 'HDU · HANGZHOU · 中国',
    passType: 'ПРЕПОДАВАТЕЛЬ В КИТАЕ',
    period: '06.2024 · 1 month',
    venue: 'HDU campus · web · AI · EN',
    icon: '🇨🇳',
    regNo: 'CHN.HDU.24',
    bg: '#b8001f', fg: '#fff7c2', accent: '#ffd23a',
    ribbon: '#1a1a1a', ribbonPattern: 'lines',
    pattern: 'vlines',
    cats: ['teach'],
    stamp: 'VISA · 签',
    stampClass: 'red',
    eyebrow: 'КИТАЙ · ХАНЧЖОУ · 1 МЕСЯЦ',
    title: 'Преподаватель в Китае',
    color: '#e63946', darkHeader: true,
    body: '<p>Мне посчастливилось побывать в Китае в качестве преподавателя в течение <b>целого месяца</b>.</p><p>У факультета ПИиКТ есть совместная программа с Китайским Университетом <b>HDU</b>. Почти целый месяц я провела в <b>Ханчжоу</b>, где каждый день вместе с коллегами вела занятия и принимала лабы у студентов разных курсов по вебу, информатике, программированию и AI <b>на английском языке</b>.</p><p>Это был, наверное, самый невероятный опыт в моей жизни. Стать преподавателем в другой стране на иностранном языке — это очень круто.</p>',
    tags: ['HDU', 'Ханчжоу', 'преподавание', 'английский', 'AI · веб'],
    stats: [['1', 'месяц'], ['4', 'предмета'], ['EN', 'язык']],
    photos: [
      ['images/china/1_IMG_7133.jpg', 'кампус HDU · Ханчжоу'],
      ['images/china/2_IMG_6971.jpg', 'лекция на английском'],
      ['images/china/3_IMG_6982.jpg', 'практика по вебу'],
      ['images/china/4_IMG_7033.jpg', 'будни в Ханчжоу'],
      ['images/china/5_IMG_7591.jpg', 'На выходных в Шанхай'],
    ]
  },

  {
    id: 'volunteer',
    org: 'ITMO · VOLUNTEER',
    passType: 'ВОЛОНТЕР',
    period: '2020 — 2026',
    venue: 'ITMO events · volunteer',
    icon: '🤝',
    regNo: 'VOL.ITMO',
    bg: '#1a4a6a', fg: '#e0f4ff', accent: '#4fc3f7',
    ribbon: '#0d2a3f', ribbonPattern: 'dots',
    pattern: 'dots',
    cats: ['participant'],
    eyebrow: 'ВОЛОНТЕРСТВО · ИТМО',
    title: 'Волонтер',
    color: '#4fc3f7', darkHeader: false,
    body: '<p>Посвяты для первокурсников, Дни открытых дверей, хакатоны, олимпиады, выезды в Ягодное — это лишь часть мероприятий, на которых мне удалось побывать в качестве волонтера, а мерч уже занял большую часть гардероба, но, попробовав однажды, остановиться уже невозможно)</p>',
    tags: ['волонтер', 'мероприятия', 'ИТМО'],
    stats: [],
    photos: [
      ['images/volonteer/1_IMG_2785.PNG', 'волонтерская смена'],
      ['images/volonteer/2_IMG_2786.PNG', 'мероприятие'],
    ]
  }
];
